# Generated by Django 3.2.8 on 2022-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('n_Consultorio', models.IntegerField(verbose_name='N_Consultorio')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
    ]
