# Generated by Django 3.2.8 on 2022-04-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Eps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAppointment', models.DateField(verbose_name='Fecha_Cita')),
                ('idUser', models.IntegerField(verbose_name='Id_Usuario')),
                ('n_Room', models.IntegerField(verbose_name='N_Consultorio')),
                ('name_Doctor', models.CharField(max_length=100, verbose_name='Nombre_Doctor')),
                ('specialty_Doctor', models.CharField(max_length=100, verbose_name='Especialidad_Doctor')),
                ('modality', models.CharField(max_length=100, verbose_name='Modalidad')),
                ('stated', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cel', models.IntegerField(verbose_name='Celular')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('adress', models.CharField(max_length=100, verbose_name='Direccion')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('sede', models.CharField(max_length=100, verbose_name='Sede')),
                ('tipeUser', models.CharField(max_length=100, verbose_name='Tipo_Usuario')),
                ('tipeContract', models.CharField(max_length=100, verbose_name='Tipo_Contrato')),
                ('plan', models.CharField(max_length=100, verbose_name='Plan')),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='celular',
            new_name='cel',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='n_Consultorio',
            new_name='n_Room',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='especialidad',
            new_name='specialty',
        ),
    ]
