# Generated by Django 3.2.8 on 2022-04-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_Eps', '0002_auto_20220415_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='specialty_Doctor',
            new_name='especialidad_Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='stated',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dateAppointment',
            new_name='fecha_Cita',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='idUser',
            new_name='id_Usuario',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='modality',
            new_name='modalidad',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='n_Room',
            new_name='n_Consultorio',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='name_Doctor',
            new_name='nombre_Doctor',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='cel',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='n_Room',
            new_name='n_Consultorio',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cel',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tipeContract',
            new_name='tipo_Contrato',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tipeUser',
            new_name='tipo_Usuario',
        ),
    ]
