# Generated by Django 3.2.8 on 2022-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_Eps', '0004_alter_doctor_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.BigIntegerField(verbose_name='Celular'),
        ),
    ]
